# Generated by Django 5.2.4 on 2026-09-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
