# Generated by Django 5.2.4 on 2026-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_apple_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
