# Generated by Django 5.2 on 2025-06-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.CharField(default='Sin dirección', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
