# Generated by Django 5.2 on 2025-08-14 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='cafe',
            index=models.Index(fields=['location'], name='reviews_caf_locatio_ea1322_idx'),
        ),
        migrations.AddIndex(
            model_name='cafe',
            index=models.Index(fields=['visibility_level'], name='reviews_caf_visibil_332ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='cafe',
            index=models.Index(fields=['latitude', 'longitude'], name='reviews_caf_latitud_7d6914_idx'),
        ),
        migrations.AddIndex(
            model_name='cafe',
            index=models.Index(fields=['owner'], name='reviews_caf_owner_i_b61659_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['cafe'], name='reviews_rev_cafe_id_7b35d6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx'),
        ),
    ]
