# Generated by Django 5.2.1 on 2025-06-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_cafe_description_remove_cafe_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.cafe'),
        ),
    ]
