# Generated by Django 5.2 on 2025-08-15 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_tag_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
