# Generated by Django 5.2 on 2025-08-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_cafe_created_at_cafe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='accepts_cards',
            field=models.BooleanField(default=False, verbose_name='Acepta tarjetas'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='accepts_reservations',
            field=models.BooleanField(default=False, verbose_name='Acepta reservas'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='brunch',
            field=models.BooleanField(default=False, verbose_name='Brunch'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='gluten_free_options',
            field=models.BooleanField(default=False, verbose_name='Opciones sin gluten'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_baby_changing',
            field=models.BooleanField(default=False, verbose_name='Cambiador para bebés'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_power_outlets',
            field=models.BooleanField(default=False, verbose_name='Enchufes disponibles'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='laptop_friendly',
            field=models.BooleanField(default=False, verbose_name='Apto para trabajar'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='quiet_space',
            field=models.BooleanField(default=False, verbose_name='Espacio tranquilo'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='specialty_coffee',
            field=models.BooleanField(default=False, verbose_name='Café de especialidad'),
        ),
    ]
