# Generated by Django 5.2.1 on 2025-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/'),
        ),
    ]
