# Generated by Django 5.2 on 2025-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_cafe_photo1_cafe_photo2_cafe_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
