# Generated by Django 5.2 on 2025-08-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_cafe_accepts_cards_cafe_accepts_reservations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='reviews.cafe')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cafe', 'date')},
            },
        ),
    ]
