# Generated by Django 5.2.4 on 2025-08-25 23:44

import django.core.validators
import django.db.models.deletion
import reviews.claims
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_cafestat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='claim_status',
            field=models.CharField(choices=[('UNCLAIMED', 'Sin reclamar'), ('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado'), ('DISPUTED', 'En disputa')], default='UNCLAIMED', max_length=12),
        ),
        migrations.AddField(
            model_name='cafe',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafes_claimed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNCLAIMED', 'Sin reclamar'), ('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado'), ('DISPUTED', 'En disputa')], default='PENDING', max_length=12)),
                ('method', models.CharField(choices=[('EMAIL_DOMAIN', 'Email del negocio'), ('PHOTO_CODE', 'Fotos con código del día'), ('PHONE', 'Verificación telefónica')], max_length=20)),
                ('email_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('token_hash', models.CharField(blank=True, max_length=128)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes_user', models.TextField(blank=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='reviews.cafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('cafe', 'user', 'status')},
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reviews.claims.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='reviews.claimrequest')),
            ],
        ),
    ]
