# Generated by Django 5.2 on 2025-06-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_cafe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
