# Generated by Django 5.2.4 on 2025-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_cafe_claim_status_cafe_claimed_by_claimrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='email',
            field=models.EmailField(blank=True, help_text='Se usa para verificar al dueño por dominio (no se muestra públicamente).', max_length=254, null=True, verbose_name='Email del negocio'),
        ),
    ]
