# Generated by Django 5.2 on 2025-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_owner_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='has_outdoor_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_vegan_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
