# Generated by Django 5.2.4 on 2025-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_reviewlike_reviewreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='precio_capuccino',
            field=models.PositiveIntegerField(blank=True, help_text='Precio pagado por un capuccino mediano', null=True),
        ),
    ]
