# Generated by Django 5.2 on 2025-06-12 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_cafe_has_outdoor_seating_cafe_has_wifi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_cafes', to=settings.AUTH_USER_MODEL),
        ),
    ]
