# Generated by Django 5.2 on 2025-12-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_precio_capuccino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('sensorial', '🧠 Sensorial / Emocional'), ('estetica', '🌿 Estética y detalles'), ('experiencia', '✍️ Actividades y experiencia')], max_length=20),
        ),
    ]
