# Generated by Django 5.2.1 on 2025-06-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_cafe_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='photo1_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='photo2_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='photo3_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
