# Generated by Django 5.2 on 2025-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_cafe_photo1_title_cafe_photo2_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cafes', to='reviews.tag'),
        ),
    ]
