# Generated by Django 5.2 on 2026-01-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_tag_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='brunch',
            new_name='serves_brunch',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='gluten_free_options',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='has_gluten_free',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='specialty_coffee',
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_gluten_free_options',
            field=models.BooleanField(default=False, verbose_name='Opciones sin gluten / Sin TACC'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='offers_ice_cream',
            field=models.BooleanField(default=False, verbose_name='Ofrece helados'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi disponible'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Apto mascotas'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_vegan_friendly',
            field=models.BooleanField(default=False, verbose_name='Opciones veganas'),
        ),
    ]
