# Generated by Django 5.2 on 2025-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_tag_cafe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
