# Generated by Django 5.2.4 on 2026-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_rename_brunch_cafe_serves_brunch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_curated',
            field=models.BooleanField(default=False, help_text='Café destacado manualmente por Gota'),
        ),
    ]
