# Generated by Django 5.2.4 on 2026-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_cafe_is_curated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuario de Instagram sin @ (ej: cafepepito)', max_length=50),
        ),
    ]
