# Generated by Django 5.2.1 on 2025-06-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_cafe_latitude_cafe_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='has_artisanal_pastries',
            field=models.BooleanField(default=False, verbose_name='Pastelería artesanal'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_gluten_free',
            field=models.BooleanField(default=False, verbose_name='Sin TACC / Gluten Free'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_specialty_coffee',
            field=models.BooleanField(default=False, verbose_name='Café de especialidad'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_vegetarian_options',
            field=models.BooleanField(default=False, verbose_name='Opciones vegetarianas'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_outdoor_seating',
            field=models.BooleanField(default=False, verbose_name='Mesas al aire libre'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet friendly'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_vegan_friendly',
            field=models.BooleanField(default=False, verbose_name='Vegano friendly'),
        ),
    ]
