# Generated by Django 5.2 on 2025-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_cafe_has_artisanal_pastries_cafe_has_gluten_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Aire acondicionado'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_books_or_games',
            field=models.BooleanField(default=False, verbose_name='Libros o juegos disponibles'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Estacionamiento disponible'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_accessible',
            field=models.BooleanField(default=False, verbose_name='Accesible para personas con movilidad reducida'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='serves_alcohol',
            field=models.BooleanField(default=False, verbose_name='Sirve alcohol'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='serves_breakfast',
            field=models.BooleanField(default=False, verbose_name='Sirve desayuno'),
        ),
    ]
