# Generated by Django 5.2.4 on 2026-02-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_cafe_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('sensorial', '☕ Sensorial'), ('experiencia', '✍️ Experiencia'), ('ambiente', '🪑 Ambiente')], max_length=20),
        ),
    ]
