# Generated by Django 5.2.1 on 2025-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_cafe_has_air_conditioning_cafe_has_books_or_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='visibility_level',
            field=models.IntegerField(choices=[(0, 'Gratis'), (1, 'Destacado'), (2, 'Premium')], default=0),
        ),
    ]
