# Generated by Django 5.2.4 on 2026-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='best_for_plan',
            field=models.CharField(blank=True, choices=[('trabajar', '💻 Trabajar o estudiar'), ('al_paso', '🚶\u200d♂️ Café al paso'), ('amigos', '💬 Charlar con amigos'), ('cita', '❤️ Cita'), ('leer', '📖 Leer o desconectar')], max_length=20, null=True, verbose_name='¿Para qué plan es mejor este café?'),
        ),
    ]
