# Generated by Django 5.2 on 2025-07-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_cafe_visibility_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='reviews.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('sensorial', '☕ Experiencia sensorial'), ('ambiente', '💬 Ambiente humano'), ('hacer', '✍️ Para hacer cosas'), ('estetica', '🌿 Estética y atmósfera'), ('emocional', '🧠 Estados mentales')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
