# Generated by Django 5.2.4 on 2026-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_review_best_for_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='best_for_plan',
            field=models.CharField(blank=True, choices=[('trabajar', '💻 Trabajar o estudiar'), ('al_paso', '🚶 Tomar algo rápido'), ('amigos', '💬 Charlar con amigos'), ('cita', '❤️ Cita'), ('leer', '📖 Leer o desconectar'), ('solo', '☕ Salir solo')], max_length=20, null=True, verbose_name='¿Para qué plan es mejor este café?'),
        ),
    ]
