# Generated by Django 5.2.4 on 2026-05-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alter_review_best_for_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='favorites',
        ),
        migrations.CreateModel(
            name='CafeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_go', '☕ Quiero ir'), ('want_to_return', '❤️ Quiero volver'), ('visited', '✔️ Ya fui')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='reviews.cafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cafe')},
            },
        ),
    ]
