# Generated by Django 5.2.4 on 2026-05-17 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_remove_cafe_favorites_caferelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caferelationship',
            name='last_status_change_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caferelationship',
            name='private_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caferelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caferelationship',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caferelationship',
            name='would_return',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caferelationship',
            name='would_return_answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='caferelationship',
            index=models.Index(fields=['user', 'status'], name='reviews_caf_user_id_18f505_idx'),
        ),
        migrations.AddIndex(
            model_name='caferelationship',
            index=models.Index(fields=['updated_at'], name='reviews_caf_updated_2ebdb5_idx'),
        ),
    ]
