# Generated by Django 5.2.4 on 2026-05-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_caferelationship_last_status_change_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caferelationship',
            name='second_impression',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
