# Generated by Django 5.2.4 on 2026-05-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_caferelationship_second_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='caferelationship',
            name='collection',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
