# Generated by Django 5.2.4 on 2026-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_cafewhisper'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='province',
            field=models.CharField(default='Buenos Aires', max_length=100, verbose_name='Provincia'),
        ),
    ]
