# Generated by Django 5.2.4 on 2026-08-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_alter_cafe_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='Con jardín'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_healthy_options',
            field=models.BooleanField(default=False, verbose_name='Opciones saludables'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_large_windows',
            field=models.BooleanField(default=False, verbose_name='Grandes ventanales'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_mountain_view',
            field=models.BooleanField(default=False, verbose_name='Vista a las sierras / montañas'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_plant_based_milk',
            field=models.BooleanField(default=False, verbose_name='Leches vegetales'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_rooftop',
            field=models.BooleanField(default=False, verbose_name='Terraza o rooftop'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_sugar_free_options',
            field=models.BooleanField(default=False, verbose_name='Opciones sin azúcar'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_water_view',
            field=models.BooleanField(default=False, verbose_name='Vista al agua'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='inside_bookstore',
            field=models.BooleanField(default=False, verbose_name='Dentro de una librería'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='inside_cultural_space',
            field=models.BooleanField(default=False, verbose_name='En un espacio cultural'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_historic_building',
            field=models.BooleanField(default=False, verbose_name='En un edificio histórico'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_kids_friendly',
            field=models.BooleanField(default=False, verbose_name='Kids friendly'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_old_house',
            field=models.BooleanField(default=False, verbose_name='En una casa antigua'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='surrounded_by_nature',
            field=models.BooleanField(default=False, verbose_name='Rodeado de naturaleza'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet friendly'),
        ),
    ]
