# Generated by Django 5.2.4 on 2026-09-07 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_alter_cafe_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('want_to_go', 'Quiero ir'), ('relationship_progress', 'Ya fui / Quiero volver'), ('check_in', 'Estoy acá'), ('review', 'Dejar reseña'), ('photo', 'Agregar foto'), ('whisper', 'Dejar huella')], max_length=30, unique=True, verbose_name='Acción')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Gotas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('max_rewards_per_window', models.PositiveIntegerField(blank=True, help_text='Dejar vacío si esta acción no tiene límite por ventana.', null=True, verbose_name='Máximo de recompensas por ventana')),
                ('window_hours', models.PositiveIntegerField(blank=True, help_text='Ejemplo: 24 para limitar recompensas dentro de una ventana de 24 horas.', null=True, verbose_name='Duración de la ventana (horas)')),
                ('repeat_after_days', models.PositiveIntegerField(blank=True, help_text='Dejar vacío si la recompensa sólo puede obtenerse una vez por cafetería.', null=True, verbose_name='Puede volver a sumar después de (días)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Gotas',
                'verbose_name_plural': 'Reglas de Gotas',
                'ordering': ['action'],
            },
        ),
        migrations.CreateModel(
            name='RewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_radius_meters', models.PositiveIntegerField(default=150, help_text='Distancia máxima entre el usuario y la cafetería para validar una visita.', verbose_name='Radio máximo para Estoy acá (metros)')),
                ('check_in_valid_hours', models.PositiveIntegerField(default=24, help_text='Durante cuántas horas una visita validada puede habilitar recompensas como una reseña.', verbose_name='Vigencia del Estoy acá (horas)')),
                ('welcome_reward_radius_km', models.FloatField(default=3.0, help_text='Si la cafetería elegida no tiene beneficio, buscar uno cercano dentro de este radio.', verbose_name='Radio para beneficio inicial (km)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de recompensas',
                'verbose_name_plural': 'Configuración de recompensas',
            },
        ),
        migrations.CreateModel(
            name='CafeReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre interno')),
                ('reward_type', models.CharField(choices=[('percentage', 'Descuento porcentual'), ('fixed_amount', 'Descuento fijo'), ('free_product', 'Producto gratis'), ('two_for_one', '2x1'), ('special_price', 'Precio especial'), ('custom', 'Beneficio personalizado')], max_length=30, verbose_name='Tipo de beneficio')),
                ('unlock_type', models.CharField(choices=[('points', 'Por Gotas'), ('automatic', 'Automático')], default='points', max_length=20, verbose_name='Forma de desbloqueo')),
                ('points_required', models.PositiveIntegerField(blank=True, help_text='Dejar vacío si el beneficio se desbloquea automáticamente.', null=True, verbose_name='Gotas necesarias')),
                ('percentage_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentaje de descuento')),
                ('fixed_amount_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Monto de descuento')),
                ('user_text', models.CharField(help_text='Ejemplo: 20% de descuento en tu consumo.', max_length=200, verbose_name='Texto para mostrar al usuario')),
                ('terms', models.TextField(blank=True, verbose_name='Condiciones')),
                ('is_welcome_reward', models.BooleanField(default=False, verbose_name='Puede usarse como primer beneficio')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Menor número = mayor prioridad cuando haya varios beneficios posibles.', verbose_name='Prioridad')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para stock ilimitado.', null=True, verbose_name='Cantidad disponible')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('coupon_valid_days', models.PositiveIntegerField(default=7, help_text='Cantidad de días que tendrá el usuario para usarlo desde que lo recibe.', verbose_name='Vencimiento del cupón (días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='reviews.cafe', verbose_name='Cafetería')),
            ],
            options={
                'verbose_name': 'Beneficio de cafetería',
                'verbose_name_plural': 'Beneficios de cafeterías',
                'ordering': ['priority', 'cafe__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('qr_token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token QR')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('used', 'Usado'), ('expired', 'Vencido'), ('cancelled', 'Cancelado')], default='available', max_length=20, verbose_name='Estado')),
                ('reward_text_snapshot', models.CharField(max_length=200, verbose_name='Beneficio otorgado')),
                ('terms_snapshot', models.TextField(blank=True, verbose_name='Condiciones al momento de otorgarlo')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='Obtenido')),
                ('expires_at', models.DateTimeField(verbose_name='Vence')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='reviews.cafe', verbose_name='Cafetería')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_coupons', to='reviews.cafereward', verbose_name='Beneficio original')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cupón de usuario',
                'verbose_name_plural': 'Cupones de usuarios',
                'ordering': ['-obtained_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('want_to_go', 'Quiero ir'), ('relationship_progress', 'Ya fui / Quiero volver'), ('check_in', 'Estoy acá'), ('review', 'Dejar reseña'), ('photo', 'Agregar foto'), ('whisper', 'Dejar huella')], max_length=30, verbose_name='Acción')),
                ('points', models.IntegerField(verbose_name='Gotas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gota_transactions', to='reviews.cafe', verbose_name='Cafetería')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gota_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Gotas',
                'verbose_name_plural': 'Movimientos de Gotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitud detectada')),
                ('longitude', models.FloatField(verbose_name='Longitud detectada')),
                ('distance_meters', models.FloatField(verbose_name='Distancia a la cafetería (m)')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Visita validada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='reviews.cafe', verbose_name='Cafetería')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_checkins', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Visita validada',
                'verbose_name_plural': 'Visitas validadas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'cafe', 'created_at'], name='reviews_caf_user_id_e08970_idx'), models.Index(fields=['user', 'is_valid'], name='reviews_caf_user_id_9049c8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cafereward',
            index=models.Index(fields=['cafe', 'is_active'], name='reviews_caf_cafe_id_fd416b_idx'),
        ),
        migrations.AddIndex(
            model_name='cafereward',
            index=models.Index(fields=['is_welcome_reward', 'is_active'], name='reviews_caf_is_welc_c68571_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['user', 'status'], name='reviews_use_user_id_c527be_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['cafe', 'status'], name='reviews_use_cafe_id_52bcea_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['qr_token'], name='reviews_use_qr_toke_278cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['expires_at'], name='reviews_use_expires_235068_idx'),
        ),
        migrations.AddIndex(
            model_name='userpointtransaction',
            index=models.Index(fields=['user', 'action', 'created_at'], name='reviews_use_user_id_a80607_idx'),
        ),
        migrations.AddIndex(
            model_name='userpointtransaction',
            index=models.Index(fields=['user', 'cafe', 'action'], name='reviews_use_user_id_cca3b7_idx'),
        ),
    ]
