# Generated by Django 5.2.4 on 2026-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_rewardactionrule_rewardsettings_cafereward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsettings',
            name='program_starts_at',
            field=models.DateTimeField(blank=True, help_text='Las acciones anteriores a esta fecha no forman parte de la economía oficial de Gotas.', null=True, verbose_name='Inicio oficial del programa'),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='rewards_enabled',
            field=models.BooleanField(default=False, help_text='Interruptor maestro. Mientras esté desactivado, ninguna acción otorga Gotas ni beneficios.', verbose_name='Programa de Gotas activo'),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='welcome_reward_enabled',
            field=models.BooleanField(default=False, help_text='Permite entregar el beneficio inicial en la primera acción elegible realizada desde el inicio del programa.', verbose_name='Beneficio de bienvenida activo'),
        ),
    ]
