# Generated by Django 5.2.4 on 2026-09-09 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_alter_rewardactionrule_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.UniqueConstraint(fields=('user', 'reward'), name='unique_user_reward_coupon'),
        ),
    ]
