# Generated by Django 5.2.4 on 2026-09-11 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_userblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeWhisperReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Contenido ofensivo'), ('false_info', 'Información falsa'), ('other', 'Otro')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whisper_reports', to=settings.AUTH_USER_MODEL)),
                ('whisper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.cafewhisper')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'whisper'), name='unique_whisper_report')],
            },
        ),
    ]
