# Generated by Django 5.2.4 on 2026-09-19 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_cafewhisperreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha aproximada de visita')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicación del usuario')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to='reviews.cafe', verbose_name='Cafetería')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reward_claims', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_claims', to='reviews.review', verbose_name='Reseña relacionada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reclamo de Gotas',
                'verbose_name_plural': 'Reclamos de Gotas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reviews_rew_status_24056e_idx'), models.Index(fields=['user', 'cafe'], name='reviews_rew_user_id_671a2b_idx')],
            },
        ),
    ]
