# Generated by Django 5.2.4 on 2026-09-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_rewardclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardclaim',
            name='review_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reward_claims', to='reviews.userpointtransaction', verbose_name='Movimiento por reseña'),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='tag_bonus_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_bonus_reward_claims', to='reviews.userpointtransaction', verbose_name='Movimiento por bonus de etiquetas'),
        ),
    ]
