# Generated by Django 5.2.4 on 2026-09-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_rewardclaim_review_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewardUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_required', models.PositiveIntegerField(verbose_name='Hito de Gotas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de elección'), ('claimed', 'Beneficio elegido')], default='pending', max_length=20, verbose_name='Estado')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Desbloqueado')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Beneficio elegido')),
                ('coupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_unlock', to='reviews.usercoupon', verbose_name='Cupón elegido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_unlocks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Beneficio desbloqueado',
                'verbose_name_plural': 'Beneficios desbloqueados',
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reviews_use_user_id_b40b75_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'points_required'), name='unique_user_reward_unlock')],
            },
        ),
    ]
