# Generated by Django 5.2.4 on 2026-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0034_userrewardunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsettings',
            name='reward_extended_radius_km',
            field=models.FloatField(default=25.0, verbose_name='Radio ampliado para beneficios (km)'),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='reward_nearby_radius_km',
            field=models.FloatField(default=10.0, verbose_name='Radio cercano para beneficios (km)'),
        ),
    ]
