# Generated by Django 5.2.4 on 2026-09-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_rewardsettings_reward_extended_radius_km_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercoupon',
            name='unique_user_reward_coupon',
        ),
    ]
