# Generated by Django 5.2.4 on 2026-09-21 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0036_remove_usercoupon_unique_user_reward_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rewardclaim',
            constraint=models.UniqueConstraint(fields=('review',), name='unique_reward_claim_per_review'),
        ),
    ]
