# Generated by Django 5.2.4 on 2026-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0037_rewardclaim_unique_reward_claim_per_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsettings',
            name='reward_thresholds',
            field=models.CharField(default='15,30,50,75,100,125,150,175,200', help_text='Hitos acumulados que desbloquean un beneficio. Separar los valores con comas. Ejemplo: 15,30,50,75,100,125', max_length=500, verbose_name='Hitos de beneficios (Gotas)'),
        ),
    ]
