# Generated by Django 5.2.4 on 2026-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0038_rewardsettings_reward_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsettings',
            name='reward_repeat_every',
            field=models.PositiveIntegerField(default=25, help_text='Después del último hito configurado, se desbloquea un nuevo beneficio cada esta cantidad de Gotas. Ejemplo: con último hito 200 y valor 25: 225, 250, 275, 300...', verbose_name='Frecuencia de beneficios después del último hito'),
        ),
    ]
