# Generated by Django 5.2.4 on 2026-10-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0039_rewardsettings_reward_repeat_every'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafereward',
            name='points_required',
        ),
    ]
