# Generated by Django 5.2.4 on 2026-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0040_remove_cafereward_points_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrewardunlock',
            name='unlock_type',
            field=models.CharField(choices=[('milestone', 'Hito de Gotas'), ('welcome', 'Beneficio de bienvenida')], default='milestone', max_length=20, verbose_name='Tipo de desbloqueo'),
        ),
        migrations.AlterField(
            model_name='userrewardunlock',
            name='points_required',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hito de Gotas'),
        ),
    ]
