# Generated by Django 5.2.4 on 2026-10-03 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0041_userrewardunlock_unlock_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrewardunlock',
            name='unique_user_reward_unlock',
        ),
        migrations.AddConstraint(
            model_name='userrewardunlock',
            constraint=models.UniqueConstraint(condition=models.Q(('unlock_type', 'milestone')), fields=('user', 'points_required'), name='unique_user_milestone_unlock'),
        ),
        migrations.AddConstraint(
            model_name='userrewardunlock',
            constraint=models.UniqueConstraint(condition=models.Q(('unlock_type', 'welcome')), fields=('user',), name='unique_user_welcome_unlock'),
        ),
    ]
