# Generated by Django 5.2.4 on 2026-10-03 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0042_remove_userrewardunlock_unique_user_reward_unlock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrewardunlock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('points_required__isnull', False), ('unlock_type', 'milestone')), models.Q(('points_required__isnull', True), ('unlock_type', 'welcome')), _connector='OR'), name='valid_user_reward_unlock_type_points'),
        ),
    ]
