# Generated by Django 5.2.4 on 2026-10-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0043_userrewardunlock_valid_user_reward_unlock_type_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardactionrule',
            name='action',
            field=models.CharField(choices=[('want_to_go', 'Quiero ir'), ('relationship_progress', 'Ya fui / Quiero volver'), ('check_in', 'Estoy acá'), ('review', 'Dejar reseña'), ('photo', 'Agregar foto'), ('whisper', 'Dejar huella'), ('review_tag_bonus', 'Bonus reseña con etiquetas'), ('manual_adjustment', 'Ajuste manual')], max_length=30, unique=True, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='userpointtransaction',
            name='action',
            field=models.CharField(choices=[('want_to_go', 'Quiero ir'), ('relationship_progress', 'Ya fui / Quiero volver'), ('check_in', 'Estoy acá'), ('review', 'Dejar reseña'), ('photo', 'Agregar foto'), ('whisper', 'Dejar huella'), ('review_tag_bonus', 'Bonus reseña con etiquetas'), ('manual_adjustment', 'Ajuste manual')], max_length=30, verbose_name='Acción'),
        ),
    ]
